CREATE TABLE "users" (
  "id" uuid PRIMARY KEY DEFAULT (uuid_generate_v4()),
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "first_name" varchar,
  "last_name" varchar,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "description" text
);

CREATE TABLE "permissions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "slug" varchar UNIQUE NOT NULL,
  "description" text
);

CREATE TABLE "role_permissions" (
  "role_id" integer,
  "permission_id" integer,
  "primary" key(role_id,permission_id)
);

CREATE TABLE "user_roles" (
  "user_id" uuid,
  "role_id" integer,
  "primary" key(user_id,role_id)
);

CREATE TABLE "drivers" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid UNIQUE,
  "license_number" varchar UNIQUE,
  "license_expiry" date,
  "health_cert_expiry" date,
  "status" varchar
);

CREATE TABLE "vehicles" (
  "id" uuid PRIMARY KEY,
  "plate" varchar UNIQUE NOT NULL,
  "brand" varchar,
  "model" varchar,
  "year" integer,
  "type" varchar,
  "vtv_expiry" date,
  "insurance_expiry" date,
  "status" varchar
);

CREATE TABLE "trips" (
  "id" uuid PRIMARY KEY,
  "driver_id" uuid,
  "vehicle_id" uuid,
  "remolque_id" uuid,
  "status" varchar,
  "origin_address" text,
  "destination_address" text,
  "estimated_start_date" timestamp,
  "actual_start_date" timestamp,
  "actual_end_date" timestamp,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "documents" (
  "id" uuid PRIMARY KEY,
  "entity_type" varchar NOT NULL,
  "entity_id" uuid NOT NULL,
  "document_type" varchar,
  "file_url" text NOT NULL,
  "metadata" jsonb,
  "uploaded_by" uuid,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "trip_costs" (
  "id" uuid PRIMARY KEY,
  "trip_id" uuid,
  "category" varchar,
  "estimated_amount" decimal(12,2),
  "actual_amount" decimal(12,2),
  "currency" varchar DEFAULT 'ARS',
  "calculation_data" jsonb,
  "notes" text
);

CREATE TABLE "alerts" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid,
  "type" varchar,
  "priority" varchar,
  "message" text,
  "is_read" boolean DEFAULT false,
  "related_entity_id" uuid,
  "created_at" timestamp DEFAULT (now())
);

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "drivers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trips" ADD FOREIGN KEY ("driver_id") REFERENCES "drivers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trips" ADD FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trips" ADD FOREIGN KEY ("remolque_id") REFERENCES "vehicles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "documents" ADD FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trip_costs" ADD FOREIGN KEY ("trip_id") REFERENCES "trips" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "alerts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
